export enum actionTypes {
    INITIAL_WEB_SOCKET = '@@game/INITIAL_WEB_SOCKET',
    SET_ALL_ROOMS = '@@game/SET_ALL_ROOMS',
    SET_CURRENT_ROOM = '@@game/SET_CURRENT_ROOM',
    CREATE_ROOM = '@@game/CREATE_ROOM',
    JOIN_ROOM = '@@game/JOIN_ROOM',
    PLAY_WITH_BOT = '@@game/PLAY_WITH_BOT',
    SET_CHECKER_DESK = '@@games/SET_CHECKER_DESK',
    SET_CURRENT_CHECKER ='@@games/SET_CURRENT_CHECKER',
}
